
name: sported_app
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  #to fix version solving
  # cupertino_icons: ^1.0.2

  # firebase
  firebase_auth: ^0.20.0+1
  cloud_firestore: ^0.16.0
  firebase_core : ^0.7.0
  firebase_storage: ^7.0.0

  # logic
  image_picker: ^0.6.7+22
  get_it: ^4.0.1
  flutter_bloc: ^6.1.2
  bloc: ^6.1.1
  equatable: ^1.2.6
  location: ^3.2.4
  geolocator: ^6.2.1
  path_provider:
  intl:
  mpesa_flutter_plugin: ^1.0.0
  connectivity_plus:

  # ui
  font_awesome_flutter: ^8.11.0
  shared_preferences: ^0.5.12+4
  palette_generator:
  flutter_spinkit: ^5.0.0
  flutter_screenutil: ^4.0.3+2
  material_design_icons_flutter: ^4.0.5855
  keyboard_avoider: ^0.1.2
  google_maps_flutter: ^1.2.0
  convex_bottom_bar: ^2.7.1
  flutter_swiper: ^1.1.6
  syncfusion_flutter_datepicker: ^18.4.44-beta
  chips_choice: ^2.0.1
  cached_network_image: ^2.5.1
  dio:
  google_sign_in: ^4.5.1
  buttons_tabbar: ^1.2.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.8.0"
  hive_generator:
  build_runner:

flutter_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/icons/sported_icon_black.png"

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/